#!/bin/bash
# Change the following values to suit your local setup.
# Add this file on your .git/hooks/ and name it as 'pre-commit'
#
# La date et heure du commit
DATE=$(date +'%m/%d/%Y %T')

echo "Date du jour : " $DATE

read -p "Créer le fichier complémentaire (y/[n]) ?" yn < /dev/tty
yn=${yn:n}
case $yn in

 [Yy]* )
	echo "commit vérifié le" $DATE > suivi/commitInfo.txt
	git add suivi/commitInfo.txt
	exit 0;;
 [Nn]* )
 	exit 0;;
esac
exit 0